package LogViewer::Web::Model::LogDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'LogViewer::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:../../db/sample.db',
        user => '',
        password => '',
    }
);

=head1 NAME

LogViewer::Web::Model::LogDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<LogViewer::Web>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<LogViewer::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48

=head1 AUTHOR

hshong

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
